In [2]:
import deepquantum as dq
import deepquantum.photonic as dqp
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [3]:
cir = dq.QumodeCircuit(nmode=2, init_state='vac', 
                       backend='gaussian', 
                       name='try', noise=False)
# cir.ps(0, 0.5)
cir.bs_real([0, 1], inputs=[torch.pi, np.nan])
# cir.bs(wires=[0, 1], inputs=[torch.pi, np.nan])

print(cir.get_unitary())

#线路可视化
cir.draw('pic/CM_circ_num_ME.svg')

tensor([[-8.7423e-08+0.j, -1.0000e+00+0.j],
        [ 1.0000e+00+0.j, -8.7423e-08+0.j]])


In [4]:
Ns = 1
Nm = 2
NL = 2
eta = 9/20*np.pi
delta_k = 0
r_k = 0
phi_k = 0

N_total = Ns + Nm + NL

# initial state
# cov = torch.eye(2*(N_total+1))
# mean = torch.zeros(2*(N_total+1))

# cir = dq.QumodeCircuit(nmode=num_ME+1, init_state=[cov, mean], 
#                        backend='gaussian', 
#                        name='try', noise=False)

cir = dq.QumodeCircuit(nmode=N_total, init_state='vac', 
                    backend='gaussian', 
                    name='try', noise=False)

# s0,m1, two-mode squeezed vacuum (TMSV) state 
# # S(r,theta)
cir.s(0, [0.1, 0.1])
# cir.s(1, [0.1, 0.1])

# m2, single-mode squeezing vacuum (SMSV) state 
# cir.s(2, [r_k, phi_k])

for i in range(N_total-2):
    for j in range(N_total-i-2):
        cir.bs_real(wires=[j+1,j+2], inputs=[eta, np.nan])
        cir.ps(j+1, [delta_k])

#线路可视化
cir.draw('pic/CM_circ_num_ME{}.svg'.format(N_total))

In [5]:
state = cir.forward()

# 这里measure_homodyne测量对应的物理量是正交算符 $$\hat x$$ 和 $$\hat p$$ 的值，
# photon_number_mean_var对应的是每个mode的光子数的平均值和方差。

# 第一个光子：x1，p1，x2，p2...
# 第二个光子：x1，p1，x2，p2...
shots = 100000
sample = cir.measure_homodyne(shots=shots)

# ( [平均值], [方差] )
photon_number = cir.photon_number_mean_var()
print('number of modes: ', N_total)
print('sample: ', sample)
print('size of sample: ', sample.size())
print('\n全部qubit的每光子数的平均值和方差: ', photon_number)

number of modes:  5
sample:  tensor([[-0.7365, -0.2070,  0.4875,  ...,  1.1798, -0.9147, -1.1344],
        [-0.5196, -0.1562, -0.3205,  ...,  1.2224, -0.6224,  0.1484],
        [ 0.2720,  1.7965, -0.9236,  ...,  2.3840,  0.2283,  1.1891],
        ...,
        [-0.6246, -1.0429, -0.4588,  ...,  0.1115,  0.1871, -0.2798],
        [ 0.3251, -0.7864, -0.5136,  ..., -0.8485, -1.0144,  0.9572],
        [-0.3243,  0.2344, -0.3707,  ..., -1.8078,  0.4156, -1.5067]])
size of sample:  torch.Size([100000, 10])

全部qubit的每光子数的平均值和方差:  (tensor([1.0033e-02, 5.9605e-08, 1.1921e-07, 1.1921e-07, 0.0000e+00]), tensor([2.0268e-02, 5.9605e-08, 1.1921e-07, 1.1921e-07, 0.0000e+00]))


In [6]:
s_xj = np.array(sample.T[0])
s_xk = np.array(sample.T[1])
m_xp = np.array(sample.T[2*1:2*(Ns+Nm)][:]) # m1x, m1p, m2x, m2p
e_xp = np.array(sample.T[2*(Ns+Nm):][:])

# print('s_xj: ', s_xj)
# print('s_xk: ', s_xk)
print('m_xp: ', m_xp)
print('e_xp: ', e_xp)

m_xp:  [[ 4.8749223e-01 -3.2054535e-01 -9.2356759e-01 ... -4.5877188e-01
  -5.1359999e-01 -3.7073940e-01]
 [-9.6791697e-01  9.6276993e-01 -1.5171512e+00 ... -2.9250050e-01
  -1.7777581e+00  8.7436682e-01]
 [ 8.8106680e-01  3.0016699e-01  1.1019255e+00 ... -1.1911688e+00
  -2.5567678e-01  5.3000677e-01]
 [-1.0393891e+00  1.1854235e-01  3.1455594e-01 ... -1.6646202e+00
   7.0002717e-01 -9.6950680e-06]]
e_xp:  [[ 1.5402956  -0.9968549   1.3447788  ... -0.68585247  0.6836393
  -2.498283  ]
 [ 1.1798184   1.222431    2.3839602  ...  0.11149672 -0.84854245
  -1.8078167 ]
 [-0.9147005  -0.62238157  0.22833341 ...  0.18712811 -1.0144132
   0.41563025]
 [-1.1344235   0.14837861  1.1890742  ... -0.27984717  0.9571514
  -1.506664  ]]


In [7]:
def get_sigma(xj, xk):
    return np.cov(xj, xk)

In [8]:
get_sigma(s_xj, s_xk)

array([[ 0.82357989, -0.00537068],
       [-0.00537068,  1.00114604]])

In [9]:
sigma_s = np.zeros((2,2))
np.size(sigma_s)

4

In [10]:
sigma_s = np.zeros((2,2))
sigma_m1 = np.zeros((2,2))
sigma_m2 = np.zeros((2,2))

sigma_s = get_sigma(s_xj, s_xk)
sigma_m1 = get_sigma(m_xp[0], m_xp[1])
sigma_m2 = get_sigma(m_xp[2], m_xp[3])
        
sigma_s, sigma_m1, sigma_m2

(array([[ 0.82357989, -0.00537068],
        [-0.00537068,  1.00114604]]),
 array([[0.99743779, 0.00547732],
        [0.00547732, 0.99845811]]),
 array([[1.00094886, 0.00451309],
        [0.00451309, 1.22763   ]]))

$$\boldsymbol{\sigma} = \begin{bmatrix}
\sigma_{xx,aa} & \sigma_{xp,aa} & \sigma_{xx,ab} & \sigma_{xp,ab} \\
\sigma_{px,aa} & \sigma_{pp,aa} & \sigma_{px,ab} & \sigma_{pp,ab} \\
\sigma_{xx,ba} & \sigma_{xp,ba} & \sigma_{xx,bb} & \sigma_{xp,bb} \\
\sigma_{px,ba} & \sigma_{pp,ba} & \sigma_{px,bb} & \sigma_{pp,bb}
\end{bmatrix}$$

In [11]:
sigma_m12 = np.zeros((2*Nm,2*Nm))
sigma_sm1 = np.zeros((2*(Ns+1),2*(Ns+1)))
sigma_sm2 = np.zeros((2*(Ns+1),2*(Ns+1)))

choose = [['xxaa', 'xpaa', 'xxab', 'xpab'],
          ['pxaa', 'ppaa', 'pxab', 'ppab'],
          ['xxba', 'xpba', 'xxbb', 'xpbb'],
          ['pxba', 'ppba', 'pxbb', 'ppbb']]
index_m12 = {'xa':m_xp[0], 'pa':m_xp[1], 'xb':m_xp[2], 'pb':m_xp[3]}
index_sm1 = {'xa':s_xj, 'pa':s_xk, 'xb':m_xp[0], 'pb':m_xp[1]}
index_sm2 = {'xa':s_xj, 'pa':s_xk, 'xb':m_xp[2], 'pb':m_xp[3]}

for i in range(Nm*2):
    for j in range(Nm*2):
        sigma_m12[i][j] = get_sigma( index_m12[choose[i][j][0]+choose[i][j][2]], 
                               index_m12[choose[i][j][1]+choose[i][j][3]] )[0][1]
        sigma_sm1[i][j] = get_sigma( index_sm1[choose[i][j][0]+choose[i][j][2]], 
                               index_sm1[choose[i][j][1]+choose[i][j][3]] )[0][1]
        sigma_sm2[i][j] = get_sigma( index_sm2[choose[i][j][0]+choose[i][j][2]],
                                 index_sm2[choose[i][j][1]+choose[i][j][3]] )[0][1]

print('sigma_m12: \n', sigma_m12)
print('sigma_sm1: \n', sigma_sm1)
print('sigma_sm2: \n', sigma_sm2)


sigma_m12: 
 [[ 0.99743779  0.00547732  0.00212001  0.00174978]
 [ 0.00547732  0.99845811  0.00125787 -0.00225131]
 [ 0.00212001  0.00125787  1.00094886  0.00451309]
 [ 0.00174978 -0.00225131  0.00451309  1.22763   ]]
sigma_sm1: 
 [[ 8.23579889e-01 -5.37068004e-03 -1.59106740e-03  3.68146345e-05]
 [-5.37068004e-03  1.00114604e+00  3.23561312e-05  7.44203197e-05]
 [-1.59106740e-03  3.23561312e-05  9.97437792e-01  5.47732065e-03]
 [ 3.68146345e-05  7.44203197e-05  5.47732065e-03  9.98458112e-01]]
sigma_sm2: 
 [[ 8.23579889e-01 -5.37068004e-03 -2.56078531e-03 -1.92292285e-02]
 [-5.37068004e-03  1.00114604e+00  1.89712503e-03  7.57352252e-04]
 [-2.56078531e-03  1.89712503e-03  1.00094886e+00  4.51308559e-03]
 [-1.92292285e-02  7.57352252e-04  4.51308559e-03  1.22763000e+00]]


$$
\boldsymbol{\sigma} = \begin{bmatrix}
\sigma_{xx,aa} & \sigma_{xp,aa} & \sigma_{xx,ab} & \sigma_{xp,ab} & \sigma_{xx,ac} & \sigma_{xp,ac} \\
\sigma_{px,aa} & \sigma_{pp,aa} & \sigma_{px,ab} & \sigma_{pp,ab} & \sigma_{px,ac} & \sigma_{pp,ac} \\
\sigma_{xx,ba} & \sigma_{xp,ba} & \sigma_{xx,bb} & \sigma_{xp,bb} & \sigma_{xx,bc} & \sigma_{xp,bc} \\
\sigma_{px,ba} & \sigma_{pp,ba} & \sigma_{px,bb} & \sigma_{pp,bb} & \sigma_{px,bc} & \sigma_{pp,bc} \\
\sigma_{xx,ca} & \sigma_{xp,ca} & \sigma_{xx,cb} & \sigma_{xp,cb} & \sigma_{xx,cc} & \sigma_{xp,cc} \\
\sigma_{px,ca} & \sigma_{pp,ca} & \sigma_{px,cb} & \sigma_{pp,cb} & \sigma_{px,cc} & \sigma_{pp,cc}
\end{bmatrix}
$$

In [12]:
sigma_sm12 = np.zeros((2*(Ns+Nm), 2*(Ns+Nm)))

choose = [['xxaa', 'xpaa', 'xxab', 'xpab', 'xxac', 'xpac'],
          ['pxaa', 'ppaa', 'pxab', 'ppab', 'pxac', 'ppac'],
          ['xxba', 'xpba', 'xxbb', 'xpbb', 'xxbc', 'xpbc'],
          ['pxba', 'ppba', 'pxbb', 'ppbb', 'pxbc', 'ppbc'],
          ['xxca', 'xpca', 'xxcb', 'xpcb', 'xxcc', 'xpcc'],
          ['pxca', 'ppca', 'pxcb', 'ppcb', 'pxcc', 'ppcc']]
index_sm12 = {'xa':s_xj, 'pa':s_xk, 'xb':m_xp[0], 'pb':m_xp[1], 'xc':m_xp[2], 'pc':m_xp[3]}

for i in range(2*(Ns+Nm)):
    for j in range(2*(Ns+Nm)):
        sigma_sm12[i][j] = get_sigma( index_sm12[choose[i][j][0]+choose[i][j][2]], 
                               index_sm12[choose[i][j][1]+choose[i][j][3]] )[0][1]

print('sigma_sm12: \n', sigma_sm12)

sigma_sm12: 
 [[ 8.23579889e-01 -5.37068004e-03 -1.59106740e-03  3.68146345e-05
  -2.56078531e-03 -1.92292285e-02]
 [-5.37068004e-03  1.00114604e+00  3.23561312e-05  7.44203197e-05
   1.89712503e-03  7.57352252e-04]
 [-1.59106740e-03  3.23561312e-05  9.97437792e-01  5.47732065e-03
   2.12000968e-03  1.74977516e-03]
 [ 3.68146345e-05  7.44203197e-05  5.47732065e-03  9.98458112e-01
   1.25787424e-03 -2.25131189e-03]
 [-2.56078531e-03  1.89712503e-03  2.12000968e-03  1.25787424e-03
   1.00094886e+00  4.51308559e-03]
 [-1.92292285e-02  7.57352252e-04  1.74977516e-03 -2.25131189e-03
   4.51308559e-03  1.22763000e+00]]


In [13]:
def f(x):
    return (x+1/2)*np.log(x+1/2) - (x-1/2)*np.log(x-1/2)

In [14]:
def S(sigma):
    from scipy import linalg
    eigvals, _ = linalg.eig(sigma)
    return np.sum(f(eigvals))

In [15]:
I2_s_m1 = S(sigma_s) + S(sigma_m1) - S(sigma_sm1)
I2_s_m2 = S(sigma_s) + S(sigma_m2) - S(sigma_sm2)
I2_s_m12 = S(sigma_s) + S(sigma_m12) - S(sigma_sm12)

I3_s_m1_m2 = I2_s_m1 + I2_s_m2 - I2_s_m12

I2_s_m1, I2_s_m2, I2_s_m12, I3_s_m1_m2

((4.476539987141592e-06+0j),
 (0.0005136879996179289+0j),
 (0.0005179324681110486+0j),
 (2.320714940218238e-07+0j))

In [16]:
from CM.TMI import TripartiteMutualInformation as tmi

a = tmi()
a.I3()

(0.00011730043855440186+0j)